#!/bin/bash

# Safely execute this bash script
# e exit on first failure
# x all executed commands are printed to the terminal
# u unset variables are errors
# a export all variables to the environment
# E any trap on ERR is inherited by shell functions
# -o pipefail | produces a failure code if any stage fails
set -Eeuoxa pipefail

# Get the directory of this script
LOCAL_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# build the docker image for the supported jobs
$LOCAL_DIRECTORY/platform/sample_job/build.sh 

#cp  slurm config files to the controller and node build context

cp -r $LOCAL_DIRECTORY/slurm_configs $LOCAL_DIRECTORY/platform/slurm_controller/
cp -r $LOCAL_DIRECTORY/slurm_configs $LOCAL_DIRECTORY/platform/slurm_node/

docker-compose -f $LOCAL_DIRECTORY/scripts/docker-compose.yaml up --build $@

