version: "3.9"
services:

  slurm_controller:
        build:
            context: ../platform/slurm_controller/
        hostname: slurm_controller
        user: admin
        volumes:
          - type: volume
            source: shared-vol
            target: /home/admin
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
                - 5001:8000
  slurm_node1:
        build:
            context: ../platform/slurm_node/
        hostname: slurm_node1
        user: admin
        volumes:
          - type: volume
            source: shared-vol
            target: /home/admin
          - type: bind
            source: /var/run/docker.sock
            target: /var/run/docker.sock
        environment:
                - SLURM_NODENAME=slurm_node1
        links:
                - slurm_controller

volumes:
        shared-vol:
