version: "3.9"
services:

  slurm_controller:
        build:
            context: ../platform/slurm_controller/
        hostname: slurm_controller
        user: admin
        volumes:
                - shared-vol:/home/admin
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
  slurm_node1:
        build:
            context: ../platform/slurm_node/
        hostname: slurm_node1
        user: admin
        volumes:
                - shared-vol:/home/admin
        environment:
                - SLURM_NODENAME=slurm_node1
        links:
                - slurm_controller

volumes:
        shared-vol:
